spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/test-person
spring.datasource.username=mara
spring.datasource.password=marapass1234!
spring.sql.init.platform=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
# show SQL queries
spring.jpa.show-sql=true
# set port
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mararusu11@gmail.com
spring.mail.password=gbmjldqkouuwmjot

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

ai.service.url=http://localhost:5000